### ISSUE TITLE
Finished assignment, but still some question marks left for me

### ISSUE THREAD

**Issue by dcswitzer** [HAN-ASD-DT/trees-assignment-dcswitzer#1]
@dvberkel I just finished the trees assignment. I needed a bit of help from the internet, al seems working now, but I don't understand some things.
For example: 

depth : Tree a -> Int
depth tree =
    case tree of
        Empty -> 0
        Node x left right -> 
           1 + max (depth left) (depth right)

I think I understand this till the part: Node x left right, where x is the root of you tree and left right are the left and right sides of the tree. 
 
As I see it now is that after that you start repeating the depth function(recursive) for the left and the right tree and for their left and right part and so on. What I don't understand is the '1 +' part, if I don't use that every outcome will be '0'. 
Could you provide some explanation?

As far as for Assignment 3 I implemented that the insert function will not insert a value if it is already part of the tree, don't know if that was your intention for this assignment.

**Comment by dvberkel** [comment]
The depth functions counts the number of steps it take to start at the root and reached the farthest leaf. So if your root is already `Empty`, i.e. a leaf, you do not have to take any steps. If it is not then you need to at least take one step, to either the left or the right sub-tree. This is were the 1 comes from.

You are right to assess that this is a recursive function. It is because the problem can reduced to simlar cases for each of the sub-trees.

**Comment by dvberkel** [comment]
Not inserting a value is fine.

An other option could be to keep track how many values of a certain number are inserted. The added bonus is that we can recreate an sorted list of all the elements that are inserted.

**Comment by dcswitzer** [comment]
Thanks for your quick reply.
